### ISSUE TITLE
Docs: Github Issues links are broken

### ISSUE THREAD

**Issue by jessefulton** [supergiant/supergiant.github.io#14]
All links in the body of https://supergiant.github.io/docs/community/github-issues-guidelines.html are improperly formatted. They have `()`'s around the URL, pointing to pages like `https://supergiant.github.io/docs/community/(https:/github.com/supergiant/supergiant.github.io/issues)` instead of `https:/github.com/supergiant/supergiant.github.io/issues`

**Comment by briansage** [comment]
Thanks for the catch @jessefulton. On it.

**Comment by briansage** [comment]
#16 should fix this.

**Comment by briansage** [comment]
Fixed in #16
